### ISSUE TITLE
use calls in global scope

### ISSUE THREAD

**Issue by ethus3h** [Fat-Zer/trinity#10]
The following ebuilds contain calls to use() in the global scope, which is no longer permitted by portage:

- `trinity-base/korganizer/korganizer-9999.ebuild`
- `trinity-base/korganizer/korganizer-3.5.13.2.ebuild`

If you could update them, that would be great :) Thanks!

**Comment by Fat-Zer** [comment]
Neither repoman nor portage doesn't complain about this and I can't find any info about it on wiki or devmanual... wouldn't it bother you to link me to a some announcement or whatever?

**Comment by ethus3h** [comment]
Yup! With [this commit to portage](https://github.com/gentoo/portage/commit/7e2f80c57ff5dc18b0737e72693e68eea4bc625e), all

**Comment by ethus3h** [comment]
(…erm, didn't mean to save it just yet.)

[all] of the helper functions, including use, are banned in global scope. That change is present in Portage 2.3.0 (but does not appear to be in 2.3.0_rc1). Thanks!

**Comment by Fat-Zer** [comment]
thanks. It revealed that I haven't updated portage; fixed
