### ISSUE TITLE
cmake-utils.eclass has dropped EAPI 3

### ISSUE THREAD

**Issue by ethus3h** [Fat-Zer/trinity#12]
With [this commit](https://gitweb.gentoo.org/repo/gentoo.git/commit/eclass/cmake-utils.eclass?id=1eab10e398ecdc8495c03e11afbb2e7cd5e3f36a), cmake-utils no longer supports EAPI 3, used by this overlay…

**Comment by Fat-Zer** [comment]
fixed in 3b4de87; thanks for reporting...

**Comment by ethus3h** [comment]
Thank you!
