### ISSUE TITLE
trinity-base/kde-i18n compilation fixes (patch provided)

### ISSUE THREAD

**Issue by calimeroteknik** [Fat-Zer/trinity#15]
The compilation of trinity-base/kde-i18n fails saying the "important program dcopidl" is missing.
So it needs a (build-time) dependency on trinity-base/kdelibs because of dcopidl.

It also needs to be more clever to detect the automake version, I patched that.
[automake-version-detection.patch.txt](https://github.com/Fat-Zer/trinity/files/1592184/automake-version-detection.patch.txt)

With this, it builds again on Gentoo current.

**Comment by SlavekB** [comment]
Note: tde-i18n can now be built using cmake.

**Comment by Fat-Zer** [comment]
Sorry I haven't respond for a while. Please redirect the patch to upstream if still relevant.

The overlay is officially dead now. Please checkout the version maintained by trinity desktop environment community: https://mirror.git.trinitydesktop.org/gitea/TDE/tde-packaging-gentoo
