### ISSUE TITLE
trinity-base/kdelibs compilation fixes (patches provided)

### ISSUE THREAD

**Issue by calimeroteknik** [Fat-Zer/trinity#16]
kdelibs needed some patching to build properly on Gentoo current. I hope I made them future-proof, as well.

[kjs-lookup-larger-value.patch.txt](https://github.com/Fat-Zer/trinity/files/1592191/kjs-lookup-larger-value.patch.txt)
[kdialogbase-casts.patch.txt](https://github.com/Fat-Zer/trinity/files/1592192/kdialogbase-casts.patch.txt)
[khtml-decoder-unsigned-char.patch.txt](https://github.com/Fat-Zer/trinity/files/1592193/khtml-decoder-unsigned-char.patch.txt)
[krsync-falsenull.patch.txt](https://github.com/Fat-Zer/trinity/files/1592194/krsync-falsenull.patch.txt)
[kshred-proper-unsigned-literals.patch.txt](https://github.com/Fat-Zer/trinity/files/1592195/kshred-proper-unsigned-literals.patch.txt)
[cups-v2-detection.patch.txt](https://github.com/Fat-Zer/trinity/files/1592196/cups-v2-detection.patch.txt)
[kserversocket-falsenull.patch.txt](https://github.com/Fat-Zer/trinity/files/1592197/kserversocket-falsenull.patch.txt)
[katebuffer-casts.patch.txt](https://github.com/Fat-Zer/trinity/files/1592198/katebuffer-casts.patch.txt)

**Comment by calimeroteknik** [comment]
Additionally this perl script fix is needed for konqueror to compile:
[dcopidl-perl-deprecated-syntax-fix.patch.txt](https://github.com/Fat-Zer/trinity/files/1592358/dcopidl-perl-deprecated-syntax-fix.patch.txt)

**Comment by SlavekB** [comment]
Please, can you compare your patches with those already integrated in the TDE r14.0.x branch?

**Comment by Fat-Zer** [comment]
Thanks for patches and sorry I haven't respond for a while. The 3.5 branch is dead for a while. If they are still relevant to current version, please redirect them to upstream.

PS: The overlay is officially dead now. Please checkout the version maintained by trinity desktop environment community: https://mirror.git.trinitydesktop.org/gitea/TDE/tde-packaging-gentoo
