### ISSUE TITLE
trinity-base/kdebase-pam license issue

### ISSUE THREAD

**Issue by sspphheerraa** [Fat-Zer/trinity#4]
As for now trinity-base/kdebase-pam/kdebase-pam-7.ebuild has LICENSE="as-is" variable. I think it's because of doubtfully.
If you check archive snapshoot of the portage tree (for example, you can get portage-20130101.tar.bz2 at http://mexmat.sgu.ru/soft/Linux/distributions/gentoo/portage/), you'll see that kde-base/kdebase-pam/kdebase-pam-7.ebuild has LICENSE="GPL-2".
And, the contents of files/ subdir are identical.

So, you can change LICENSE variable to "GPL-2" in trinity-base/kdebase-pam/kdebase-pam-7.ebuild
Meaning 'kdebase-pam' is FOSS.

**Comment by Fat-Zer** [comment]
fixed; thanks for reporting;

Note that kde-base/kdebase-pam-7 originally had license as-is as well. it was changed on https://bugs.gentoo.org/show_bug.cgi?id=441702
The overlay was created before those times...
