### ISSUE TITLE
trinity-base/tdegraphics-meta/tdegraphics-meta-9999.ebuild needs update for kiconedit rename

### ISSUE THREAD

**Issue by ethus3h** [Fat-Zer/trinity#5]
Hi! Since kiconedit is now tdeiconedit, https://github.com/Fat-Zer/trinity/blob/master/trinity-base/tdegraphics-meta/tdegraphics-meta-9999.ebuild#L27 should be:

``` >=trinity-base/kiconedit-${PV}:${SLOT}```
Thanks! :)
```

**Comment by Fat-Zer** [comment]
thanks for reporting,
fixed it locally a while ago, but was distracted testing tdegames package and forgot to commit...

**Comment by ethus3h** [comment]
Yay, thanks! And tdegames are here now! Thank you for making this overlay! :)

Just noticed I kinda screwed up my comment above, but it looks like you figured it out anyway… :3
